kubeProxyReplacement: true
k8sServiceHost: k3d-streampaicluster-server-0
k8sServicePort: 6443
operator:
  replicas: 1
envoy:
  enabled: true
  # maxRequestsPerConnection: 100
debug:
  enable: true
  verbose: envoy
l2announcements:
  enabled: true
devices: "eth0"
externalIPs:
  enabled: true
nodePort:
  enabled: true
gatewayAPI:
  enabled: true
image:
  pullPolicy: IfNotPresent
# ipam:
  # mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: false
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true