apiVersion: k3d.io/v1alpha5 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
metadata:
  name: streampaicluster # name that you want to give to your cluster (will still be prefixed with `k3d-`)
servers: 1 # same as `--servers 1`
image: rancher/k3s:v1.27.5-rc3-k3s1 # same as `--image rancher/k3s:v1.20.4-k3s1`
network: cluster-network # same as `--network my-custom-net`
subnet: "172.28.0.0/16"
registries:
  config: |
    mirrors:
      "noxy.ddns.net:5000":
        endpoint:
          - "http://noxy.ddns.net:5000"

volumes: # repeatable flags are represented as YAML lists
  - volume: /sys/fs/bpf:/sys/fs/bpf:shared # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
    nodeFilters:
      - server:*
      - agent:*
  - volume: /run/cilium/cgroupv2:/run/cilium/cgroupv2:shared # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
    nodeFilters:
      - server:*
      - agent:*
ports:
  - port: 80:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 6443:6443 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returning; same as `--wait` (default: true)
    timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
    disableLoadbalancer: false # same as `--no-lb`
    disableImageVolume: false # same as `--no-image-volume`
    disableRollback: false # same as `--no-Rollback`
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: "--disable-kube-proxy"
        nodeFilters:
          - server:*
          - agent:*
      - arg: "--disable=local-storage"
        nodeFilters:
          - server:*
          - agent:*
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
          - agent:*
      - arg: "--disable=servicelb"
        nodeFilters:
          - server:*
          - agent:*
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
          - agent:*
      - arg: "--disable-network-policy"
        nodeFilters:
          - server:*
          - agent:*
